config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }

  root 'projects#index'

  get 'search_users', to: 'users#search'

  resources :projects do 
    resources :tasks
  end

  resources :user_projects 
  get 'destroy_association' , to: 'user_projects#destroy_association'
  

end

app/models/task.rb
class Task < ActiveRecord::Base

  
     
    belongs_to :creator, :class_name => 'User'
    belongs_to :resolver, :class_name => 'User'
    belongs_to :projects , :dependent => :destroy

    validates :title, presence: true, uniqueness: true
    validates :description, presence: true
    validates :task_category , presence: true
    validates :status, presence: true
    validates :creator_id, presence: true
    validates :resolver_id, presence: true
    validates :project_id, presence: true

    mount_uploader :avatar, AvatarUploader 
  end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    helper_method :is_manager , :is_developer , :is_qa


    def index
        
        @project = Project.find(params[:project_id])
        
        if current_user.user_type == "Developer"
            @tasks = @project.tasks.where(resolver_id: current_user.id)
            @count = @tasks.count
        else
            @tasks = @project.tasks
            @count = @tasks.count
        end
    end


    def new
        if is_developer
            flash[:danger] = "you don't have right to create new task"
            redirect_to action: "index"
        end
        @project = Project.find(params[:project_id])
        @developer = User.where(user_type: "Developer")
        @count1 = @developer.count
        if @count1 == 0
            flash[:danger] = "you don't have any developer yet"
            redirect_to action: "index"
        end
        @developer_array = @developer.map { |dev| [dev.email, dev.email] } 
        @task = Task.new
    end

  
    def create
        if is_developer
            flash[:danger] = "you don't have right to create new task"
            redirect_to action: "index"
        end

        @project = Project.find(params[:project_id])
        @user = current_user
        @resolver = User.where(email: params[:developer]).first
        @task = Task.new
        @task.description = params[:description]
        @task.title = params[:title]
        @task.task_category = params[:task_category] 
        @task.status = "new"
        @task.project_id = @project.id
        @task.creator_id = @user.id
        @task.resolver_id = @resolver.id
        @task.avatar = params[:avatar]

        puts "hellon\n"*12
        puts @task.avatar_url
        puts params[:avatar]
        puts "hellon\n"*12

        if @task.save
            if !UserProject.where(user_id: @resolver.id, project_id: @project.id).first
                @user_project = UserProject.create(user: @resolver, project: @project)
            end
            flash[:success] = "Task has been Created Successfully"
            redirect_to action: "index"
            
        else      
            flash[:danger] = "#{@task.errors.full_messages}"
            redirect_to action: "new"
        end
    end


    def destroy  
        @task = Task.find(params[:id])
        @project = Project.find(params[:project_id])

        if is_developer || @task.creator_id != current_user.id
            flash[:danger] = "you don't have right to delete task"
            redirect_to action: "index"
        else

            @task.delete
            @assignedUser = User.find(@task.resolver_id)
            @assignedTaskscount = @assignedUser.resolved_tasks.count
            if @assignedTaskscount==0
                @user_project = UserProject.where(user_id: @assignedUser.id, project_id: @project.id).first
                @user_project.delete
            end
            flash[:success] = "Sucessfully deleted #{@task.title}"
            redirect_to action: "index"
        end
    end


    def edit
        @task = Task.find(params[:id])
        if @task.resolver_id!= current_user.id && @task.creator_id != current_user.id
            flash[:danger] = "you don't have right to edit this task"
            redirect_to action: "index"
        end

        @project = Project.find(params[:project_id])
        @resolver = User.where(id: @task.resolver_id).first
    end


    def update
        @task = Task.find(params[:id])
        if @task.resolver_id!= current_user.id && @task.creator_id != current_user.id
            flash[:danger] = "you don't have right to edit this task"
            redirect_to action: "index"
        else

            if @task.resolver_id != current_user.id

                if @task.update(description: params[:description] , title: params[:title] , status: params[:task_status])
                    flash[:success] = "Task has been updated Successfully"
                    redirect_to action: "index"
                    
                else      
                    flash[:danger] = "#{@task.errors.full_messages}"
                    redirect_to action: "edit"
                end
            else

                if @task.update(status: params[:task_status])
                    flash[:success] = "Task has been updated Successfully"
                    redirect_to action: "index"
                    
                else      
                    puts "hell \n" *12
                    puts @task.title
                    flash[:danger] = "#{@task.errors.full_messages}"
                    redirect_to action: "edit"
                end
            end

        end
    end


    def show 
        @task = Task.find(params[:id])
        if @task.resolver_id!= current_user.id && @task.creator_id != current_user.id
            flash[:danger] = "you don't have right to create new task"
            redirect_to action: "index"
        end
        @project = Project.find(params[:project_id])
        puts "hellon\n"*12
        puts @task.avatar_url.to_s
        puts "hellon\n"*12
        
        @task = Task.find(params[:id])
    end


    def task_params
        params.require(:task).permit(:title , :description) 
    end


    def is_manager
        current_user.user_type == "Manager"
    end

    def is_developer
        current_user.user_type == "Developer"
    end

    def is_qa
        current_user.user_type == "QA"
    end

end

app/views/tasks/edit.html.erb
<% if !is_developer %> 

<%= form_tag url_for(action: 'update'), method: "patch" do %>

    <div class="form-group row no-padding text-center col-md-12">
      
        <%= text_field_tag 'title' , @task.title , placeholder: "Task Title", autofocus: true,
                                  class: "form-control input-lg" %>      
    </div>

    <div class="form-group row no-padding text-center col-md-12">

        <%= text_area_tag 'description' , @task.description , placeholder: "Task Description", autofocus: false,
                                  class: "form-control input-lg textarea" %>      
    </div>

    <div class="form-group">
        <%= label_tag :"Task Type :  " %>
        <%= @task.task_category %>
      </div>

      <div class="form-group">
        <%= label_tag :"Resolver :  " %>
        <%= @resolver.name%>
      </div>

      <div class="form-group">
        <%= label_tag :"Status :  " %>
        <%= @task.status%>
      </div>

      <% if @task.task_category == "Featured" %>

            <div class="form-group">
                <%= label_tag :"Select New Status" %>
                <%= select_tag :task_status, options_for_select([ ["New", "New"], ["Started", "Started"], ["Completed", "Completed"]]) %>
            </div>

      <%else%>

            <div class="form-group">
                <%= label_tag :"Select New Status" %>
                <%= select_tag :task_status, options_for_select([ ["New", "New"], ["Started", "Started"], ["Resolved", "Resolved"]]) %>
            </div>

       <% end %>

      <div class="row">
      <div class="col-md-2 ">
          <%= link_to "Back to Tasks", project_tasks_path(@project), class: "button btn btn-lg btn-success" %>
      </div>

      <div class = "col-md-7">
      </div>

      <div class = "col-md-2">
          <%= submit_tag "Update Task", class: "button btn btn-lg btn-success" %>
      </div>
  </div>

<% end %>


<% else %>

<%= form_tag url_for(action: 'update'), method: "patch" do %>

        <div class="form-group">
            <%= label_tag :"Current Status :  " %>
            <%= @task.status%>
        </div>

        <% if @task.task_category == "Featured" %>

                <div class="form-group">
                    <%= label_tag :"Select New Status" %>
                    <%= select_tag :task_status, options_for_select([ ["New", "New"], ["Started", "Started"], ["Completed", "Completed"]]) %>
                </div>

        <%else%>

                <div class="form-group">
                    <%= label_tag :"Select New Status" %>
                    <%= select_tag :task_status, options_for_select([ ["New", "New"], ["Started", "Started"], ["Resolved", "Resolved"]]) %>
                </div>

        <% end %>

        <div class="row">
        <div class="col-md-2 ">
            <%= link_to "Back to Tasks", project_tasks_path(@project), class: "button btn btn-lg btn-success" %>
        </div>

        <div class = "col-md-7">
        </div>

        <div class = "col-md-2">
            <%= submit_tag "Update Task", class: "button btn btn-lg btn-success" %>
        </div>

      <% end %>

<% end %>

app/views/tasks/index.html.erb
<h3> Tasks of <%= @project.project_name %> Project </h3>

<% if is_manager || is_qa %>
    <%= link_to "Add new Task!", new_project_task_path(@project), class: "button btn btn-lg btn-success" %>
<% end %>

<% if @count>0 %>

  <table class="table table-striped">

    <thead>
      <tr>
        <th>Title</th>
        <th>Status</th>
        <th>Created By</th>
        <th>Assigned to</th>
        <th>Action</th>
      </tr>
    </thead>
  
    <tbody>
      <% @tasks.each do |t| %>
        <tr>
          <td><%= t.title %></td>
          <td><%= t.status %></td>
          <td><%= t.creator.email %></td>
          <td><%= t.resolver.email %></td>
          <td>
        
            <% if (is_manager || is_qa) %>

                <%= link_to "Delete this Task", project_task_path(@project,t), 
                          method: :delete,
                          data: {confirm: "Are you sure?"}, 
                          class: "btn btn-xs btn-danger" %>

                <%= link_to "Edit this Task", edit_project_task_path(@project,t),
                      class: "btn btn-xs btn-success" %>
            <% else %>

                <%= link_to "Update Status", edit_project_task_path(@project,t),
                      class: "btn btn-xs btn-success" %>
            <% end %>      

                <%= link_to "View Detail", project_task_path(@project,t),
                          class: "btn btn-xs btn-success" %>

          </td>
            
          
        </tr>
      <% end %>
    </tbody>
  </table>


<% else %>
    <h3> This project has no task yet</h3>
<%  end %>


<div class="row">
        <div class="col-md-2 ">
            <%= link_to "Back to Projects", projects_path, class: "button btn btn-lg btn-success" %>
        </div>
</div>

app/views/tasks/new.html.erb
<%= form_tag url_for(action: 'create'), multipart: true  ,method: "post" do %>

    <div class="form-group row no-padding text-center col-md-12">
      
        <%= text_field_tag 'title' , @task.title , placeholder: "Task Title", autofocus: true,
                                  class: "form-control input-lg" %>      
    </div>

    <div class="form-group row no-padding text-center col-md-12">

        <%= text_area_tag 'description' , @task.description , placeholder: "Task Description", autofocus: false,
                                  class: "form-control input-lg textarea" %>      
    </div>


    <div class="form-group">
        <%= label_tag :"Task Type" %>
        <%= select_tag "task_category" , options_for_select([ ["Bug", "Bug"], ["Featured", "Featured"]]) %>
      </div>

      <div class="form-group">
        <%= label_tag :"Available Developers" %>
        <%= select_tag "developer" , options_for_select( @developer_array ) %>
      </div>



      <div class="form-group">
            <%= label_tag :Image %>
            <%= file_field_tag 'avatar'  %>
      </div>



      <div class="row">
      <div class="col-md-2 ">
          <%= link_to "Back to Tasks", project_tasks_path(@project), class: "button btn btn-lg btn-success" %>
      </div>

      <div class = "col-md-7">
      </div>

      <div class = "col-md-2">
          <%= submit_tag "Create Task", class: "button btn btn-lg btn-success" %>
      </div>
  </div>

<% end %>

app/views/tasks/show.html.erb
<div class= "row">
    <label>Image</label>
    <img src= <%= @task.avatar_url.to_s %> alt="rss feed" height="200" width="300"/>
</div>


<div class= "row">
    <h3> <%= @task.title %> </h3>
</div>

<div class= "row">
    <div class = "col-md-4">
        <h4>  Description: </h4>
    </div>
    <h5> <%= @task.description %> </h5>
</div>

<div class= "row">
    <div class = "col-md-4">
        <h4>  Creator: </h4>
    </div>
    <h5> <%= @task.creator.name %> </h5>
</div>

<div class= "row">
    <div class = "col-md-4">
        <h4>  Resolver: </h4>
    </div>
    <h5> <%= @task.resolver.name %> </h5>
</div>

<div class= "row">
    <div class = "col-md-4">
        <h4>  Status: </h4>
    </div>
    <h5> <%= @task.status %> </h5>
</div>

<div class= "row">
    <div class = "col-md-4">
        <h4>  Type: </h4>
    </div>
    <h5> <%= @task.task_category %> </h5>
</div>


<div class="row">
      <div class="col-md-2 ">
          <%= link_to "Back to Tasks", project_tasks_path(@project), class: "button btn btn-lg btn-success" %>
      </div>
</div>