config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }

  root 'projects#index'

  get 'search_users', to: 'users#search'

  resources :projects do 
    resources :tasks
  end

  resources :user_projects 
  get 'destroy_association' , to: 'user_projects#destroy_association'
  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :user_projects, :dependent => :destroy
  has_many :projects, through: :user_projects

  has_many :owned_tasks, :class_name => 'Task', :foreign_key => 'creator_id'
  has_many :resolved_tasks, :class_name => 'Task', :foreign_key => 'resolver_id'

  before_save { self.email = email.downcase }
  validates :name, presence: true
  validates :user_type, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 
        def self.search(param)
          #param.strip!
          #param.downcase!
          to_send_back = (name_matches(param) + email_matches(param)).uniq
          return nil unless to_send_back
          to_send_back
        end
        
        def self.name_matches(param)
          matches('name', param)
        end
        
        def self.email_matches(param)
          matches('email', param)
        end
        
        def self.matches(field_name, param)
          where("#{field_name} like ?", "%#{param}%")
        end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters
    #USERTYPE = ['Manager', 'User', 'QA']

    protected
    
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:user_type])
      devise_parameter_sanitizer.permit(:account_update, keys: [:user_type])
    end
    

    
    
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    helper_method :is_already_added , :is_manager

    def search
       # @user = User.search(params[:user])
        @project_id = params[:project_id]
        
        if params[:user].present?
            @users = User.search(params[:user]) 
            if @users.length > 0
                render partial: 'users/search'
            else
                flash.now[:danger] = "No record found"
                render partial: 'users/search'
            end
             
        else
            flash.now[:danger] = "Please enter user name or email"
            render partial: 'users/search'
        end
            
    end
 
    def is_already_added (email , project)
        @user1 = User.where(email: email).first
        @user_project = UserProject.where(user_id: @user1, project_id: project).first
    end

    

    
end

app/views/users/_search.html.erb
<div class="row">
  <div class="col-lg-9">
    <%= bootstrap_flash %>
  </div>
</div>

<% if @users %>

  <table class="table table-striped">
  
    <thead>
        <tr>
            <th>Users</th>
            <th>Roles</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
      <% @users.each do |u| %>
        <% if u.id != current_user.id && (u.user_type!="Manager" && u.user_type!="Developer") %>

          <tr>
            <td><%= u.email %></td>
            <td><%= u.user_type %></td>
            <td>
                <% if !is_already_added(u.email , @project_id)%>
                  
                      <%= link_to "Add to this project", user_projects_path(user: u.id, 
                                                        project: @project_id),
                                                        class: "btn btn-xs btn-success", 
                                                        method: :post %>
                  
                <%else%>
                      <P>Already Added </p> 
                <% end %>
            </td>
          </tr>
          
        <% end%>
      <% end %>
    </tbody>


  </table>

<% end %>