config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }

  root 'projects#index'

  get 'search_users', to: 'users#search'

  resources :projects do 
    resources :tasks
  end

  resources :user_projects 
  get 'destroy_association' , to: 'user_projects#destroy_association'
  

end

app/models/project.rb
class Project < ActiveRecord::Base

    has_many :user_projects, :dependent => :destroy
    has_many :users, through: :user_projects

    has_many :tasks, :dependent => :destroy

    validates :project_name, presence: true, uniqueness: true
    validates :description, presence: true
    validates :creator_id, presence: true

  end
  

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    helper_method :is_manager , :is_developer , :is_qa

    def index
        @user = current_user
        @projects = current_user.projects
        @count = @projects.count
    end

    def new 
        if !is_manager
            flash[:danger] = "You don't have right to create project"
            redirect_to action: "index"
        end
        @project = Project.new
    end

    def create
        if is_manager
            @project = Project.new(project_params)
            @project.creator_id = current_user.id
            if @project.save
                @user_project = UserProject.new
                @user_project.user_id = current_user.id
                @user_project.project_id = @project.id
                @user_project.save
                flash[:success] = "Sucessfully Created #{@project.project_name}"
                redirect_to action: "index"
            else      
                flash[:danger] = "#{@project.errors.full_messages}"
                redirect_to action: "new"
            end
        else      
            flash[:danger] = "You don't have right to create project"
            redirect_to action: "index"
        end
    end

    def destroy
        @project = Project.find(params[:id])
        if is_manager && @project.creator_id == current_user.id
            @project = Project.find(params[:id])
            Project.find(@project).destroy
            flash[:success] = "Sucessfully deleted #{@project.project_name}"
            redirect_to action: "index"
        else      
            flash[:danger] = "You don't have right to destroy project"
            redirect_to action: "index"
        end
    end

    def edit
        @project = Project.find(params[:id])
        if !is_manager || @project.creator_id != current_user.id
            flash[:danger] = "You don't have right to edit project"
            redirect_to action: "index"
        end
        
    end

    def update
        @project = Project.find(params[:id])
        if is_manager || @project.creator_id != current_user.id
            
            if @project.update(project_params)
                flash[:success] = "Sucessfully Updated #{@project.project_name}"
                redirect_to action: "index"
            else
                flash[:danger] = "#{@project.errors.full_messages}"
                redirect_to action: "edit"
            end
        else      
            flash[:danger] = "You don't have right to update project"
            redirect_to action: "index"
        end
    end

    def show
        @project = Project.find(params[:id])
        if is_manager || @project.creator_id == current_user.id
            
            @existing_users = @project.users
            @count1 = @existing_users.count
            if @count1>0
                @existing_users.reject {|u| u.id == current_user.id}
                @count1 = @count1 -1
            end
        else      
            flash[:danger] = "You don't have right to see info of project"
            redirect_to action: "index"
        end
    end
    
    def project_params
        params.require(:project).permit(:project_name , :description) 
    end

    def is_manager
        current_user.user_type == "Manager"
    end

    def is_developer
        current_user.user_type == "Developer"
    end

    def is_qa
        current_user.user_type == "QA"
    end
end

app/views/projects/edit.html.erb
<%= form_for @project do |f| %>
    <div class="form-group row no-padding text-center col-md-12">
      
        <%= f.text_field :project_name, placeholder: "Project Name", autofocus: true,
                                  class: "form-control input-lg" %>      
    </div>

    <div class="form-group row no-padding text-center col-md-12">

        <%= f.text_area :description, placeholder: "Project Description", autofocus: false,
                                  class: "form-control input-lg textarea" %>      
    </div>


    <div class="row">
        <div class="col-md-2 ">
            <%= link_to "Back to Projects", projects_path, class: "button btn btn-lg btn-success" %>
        </div>

        <div class = "col-md-7">
        </div>

        <div class = "col-md-2">
            <%= f.submit class: "btn btn-lg btn-success" %>
        </div>
    </div>
<% end %>

app/views/projects/index.html.erb
<h3> Projects </h3>

<% if is_manager %>
  <%= link_to "Add new Project!", new_project_path, class: "button btn btn-lg btn-success" %>
<% end %>

<% if @count>0 %>

  <table class="table table-striped">

    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>
  
    <tbody>
      <% @projects.each do |p| %>
        <tr>
          <td><%= p.project_name %></td>
          <td>
            <% if is_manager %>
              
                <%= link_to "Delete this Project", project_path(p), 
                          method: :delete,
                          data: {confirm: "Are you sure?"}, 
                          class: "btn btn-xs btn-danger" %>

                <%= link_to "Edit this Project", edit_project_path(p),
                          class: "btn btn-xs btn-success" %>

                <%= link_to "QA's", project_path(p),
                          class: "btn btn-xs btn-success" %>
            <% end %>

                <%= link_to "Tasks", project_tasks_path(p),
                          class: "btn btn-xs btn-success" %>
          </td>
            
          
        </tr>
      <% end %>
    </tbody>
  </table>


<% else %>
  <% if is_manager %>
    <h3> You do not have any project </h3>
  <%else%>
    <h3> You have not assigned any project </h3>
  <%end%>
<%  end %>

app/views/projects/new.html.erb
<%= form_for @project do |f| %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= f.text_field :project_name, placeholder: "Project Name", autofocus: true,
                                  class: "form-control input-lg" %>
      </div>
      <div class="col-md-2">
        <%= f.submit class: "btn btn-lg btn-success" %>
      </div>
    </div>
<% end %>


<h3>Your Projects</h3>

app/views/projects/show.html.erb
<div class= "row">
    <h4> Project Name :  </h4>
    <h5> <%= @project.project_name %> </h5>
</div>

<div class= "row">
    <h4> Project Description : </h4>
    <h5> <%= @project.description %> </h5>
</div>

 

<div id="user_lookup">
<%= form_tag search_users_path, remote: true, method: :get, 

                                                              id: "user-lookup-form" do %>
  <div class="form-group row no-padding text-center col-md-12">
    <div class="col-md-10">
      <%= text_field_tag :user  , params[:user] ,
 
                                placeholder: "Search User to add in this project", 
                                autofocus: true,
                                class: "form-control search-box input-lg" %>
      <%= hidden_field_tag :project_id , @project.id %>
    </div>
    <div class="col-md-2">
      <%= button_tag(type: :submit, class: "btn btn-lg btn-success" ) do %>
        <i class="fa fa-search"></i> Search User
      <% end %>
    </div>
  </div>
<% end %>
</div>


<div id = "results">

</div>





<% if @count1>0 %>
<h3> Existing Users in this Projects </h3>

<table class="table table-striped">

  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Role</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @existing_users.each do |u| %>
      <% if u.id != current_user.id && u.user_type!="Developer"%>
        <tr>
          <td><%= u.email %></td>
          <td><%= u.name %></td>
          <td><%= u.user_type %></td>
            <td>
            <%= link_to "Remove this user from this project", destroy_association_path(user: u.id, 
            project: @project.id),
            data: {confirm: "Are you sure?"}, 
            class: "btn btn-xs btn-danger" %>
            
            </td>
            
        </tr>
      <% end %>
    <% end %>
  </tbody>

</table>


<% else %>
    <h3> This project has no user </h3>
<%  end %>
<div class="row">
        <div class="col-md-2 ">
            <%= link_to "Back to Projects", projects_path, class: "button btn btn-lg btn-success" %>
        </div>
        </div> 